obstacle_range: 2.5
raytrace_range: 5.0

footprint: [[-0.1, -0.175], [-0.1, 0.175], [0.2, 0.175], [0.2, -0.175]]
# robot_radius: 0.3

inflation_radius: 0.3
cost_scaling_factor: 1.5

map_type: costmap
observation_sources: laser_scan_sensor #point_cloud_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
