DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.75
  min_vel_x: -0.2

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 1.0
  min_rot_vel: 0.2  # Adjust for slower in-place rotations

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.5
  min_vel_trans:  0.0

  max_vel_theta: 1.0
  min_vel_theta: -1.0

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 20
  controller_frequency: 10.0
  penalize_negative_x: true

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  sim_period : 0.1