local_costmap:
  transform_tolerance: 0.5  
  width: 3
  height: 3

  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 5.0
  height: 5.0
  resolution: 0.05
  static_map: false
  rolling_window: true
  # inflation_radius: 0.3
  # cost_scaling_factor: 10.0
  
